package expo.modules.memegetbg

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.media.ExifInterface
import android.net.Uri
import android.os.Debug
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Device gate for the full-resolution still exporter.
 *
 * The two plan fixtures are byte-for-byte what `buildImageRenderPlan` emits —
 * src/memeImageRenderCore.test.ts pins them against the TS builder, so this
 * test cannot drift away from production input. Only `source.uri` is patched,
 * because it has to point at a file this test just wrote.
 */
@RunWith(AndroidJUnit4::class)
class MemeImageRendererInstrumentedTest {
  private companion object {
    const val ROTATED_PLAN = "render_plan_rotated_cropped.json"
    const val TRANSPARENT_PLAN = "render_plan_transparent.json"

    /** Generated by buildCutoutParityFixtures() in src/memeImageRenderCore.ts. */
    const val CUTOUT_PARITY_FIXTURE = "cutout_parity_fixtures.json"

    /** Cutout fixtures are flat magenta so compositing is observable. */
    const val CUTOUT_COLOR = 0xFFFF00FF.toInt()
    val PNG_SIGNATURE = byteArrayOf(
      0x89.toByte(), 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A
    )

    // Fixture source quadrants (640x400).
    const val TOP_LEFT = Color.RED
    const val TOP_RIGHT = Color.GREEN
    const val BOTTOM_LEFT = Color.BLUE
    const val BOTTOM_RIGHT = Color.YELLOW

    // Large EXIF-rotated fixture, in raw (pre-orientation) pixels.
    const val LARGE_SOURCE_WIDTH = 3264
    const val LARGE_SOURCE_HEIGHT = 2448
  }

  private val instrumentation = InstrumentationRegistry.getInstrumentation()
  private val context = instrumentation.targetContext

  /**
   * 640x400 with four flat quadrants plus a 1px checkerboard patch. The
   * checkerboard is positioned so that — after the plan's 90 degree rotation
   * and crop — it lands exactly under the pixelate cover, which is what makes
   * "did the mosaic actually average pixels" answerable.
   */
  private fun writeFixtureSource(name: String): Uri {
    val bitmap = Bitmap.createBitmap(640, 400, Bitmap.Config.ARGB_8888)
    for (y in 0 until 400) {
      for (x in 0 until 640) {
        val quadrant = when {
          x < 320 && y < 200 -> TOP_LEFT
          x >= 320 && y < 200 -> TOP_RIGHT
          x < 320 -> BOTTOM_LEFT
          else -> BOTTOM_RIGHT
        }
        val checkered = x in 360 until 540 && y in 110 until 210
        bitmap.setPixel(x, y, if (checkered) (if ((x + y) % 2 == 0) Color.WHITE else Color.BLACK) else quadrant)
      }
    }
    val file = File(context.cacheDir, name)
    FileOutputStream(file).use { stream ->
      assertTrue("fixture png encoded", bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream))
    }
    bitmap.recycle()
    return Uri.fromFile(file)
  }

  private fun plan(asset: String, sourceUri: Uri): String =
    instrumentation.context.assets.open(asset).bufferedReader().use { it.readText() }
      .replace("SOURCE_URI", sourceUri.toString())

  private fun renderedFile(planJson: String): File {
    val path = MemeImageRenderer.render(context, planJson)
    val file = File(requireNotNull(Uri.parse(path).path) { "renderer returned $path" })
    assertTrue("renderer wrote $path", file.isFile && file.length() > 0)
    return file
  }

  private fun assertPngSignature(file: File) {
    val header = ByteArray(8)
    file.inputStream().use { input -> assertEquals(8, input.read(header)) }
    assertEquals(
      "PNG magic bytes",
      PNG_SIGNATURE.joinToString(",") { it.toInt().and(0xFF).toString(16) },
      header.joinToString(",") { it.toInt().and(0xFF).toString(16) }
    )
  }

  private fun decode(file: File): Bitmap = requireNotNull(
    BitmapFactory.decodeFile(
      file.absolutePath,
      BitmapFactory.Options().apply { inPreferredConfig = Bitmap.Config.ARGB_8888 }
    )
  ) { "could not decode ${file.absolutePath}" }

  /**
   * An 8 MP camera-shaped JPEG tagged EXIF orientation 6, quadrant-coloured so
   * the orientation the renderer applies is observable in the output.
   */
  private fun writeLargeExifRotatedSource(name: String): File {
    val bitmap = Bitmap.createBitmap(LARGE_SOURCE_WIDTH, LARGE_SOURCE_HEIGHT, Bitmap.Config.ARGB_8888)
    val canvas = Canvas(bitmap)
    val paint = Paint()
    val halfWidth = LARGE_SOURCE_WIDTH / 2f
    val halfHeight = LARGE_SOURCE_HEIGHT / 2f
    val quadrants = listOf(
      RectF(0f, 0f, halfWidth, halfHeight) to TOP_LEFT,
      RectF(halfWidth, 0f, LARGE_SOURCE_WIDTH.toFloat(), halfHeight) to TOP_RIGHT,
      RectF(0f, halfHeight, halfWidth, LARGE_SOURCE_HEIGHT.toFloat()) to BOTTOM_LEFT,
      RectF(halfWidth, halfHeight, LARGE_SOURCE_WIDTH.toFloat(), LARGE_SOURCE_HEIGHT.toFloat())
        to BOTTOM_RIGHT
    )
    for ((rect, color) in quadrants) {
      paint.color = color
      canvas.drawRect(rect, paint)
    }
    val file = File(context.cacheDir, name)
    FileOutputStream(file).use { stream ->
      assertTrue("fixture jpeg encoded", bitmap.compress(Bitmap.CompressFormat.JPEG, 92, stream))
    }
    bitmap.recycle()
    ExifInterface(file.absolutePath).apply {
      setAttribute(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_ROTATE_90.toString())
      saveAttributes()
    }
    return file
  }

  /**
   * Peak growth of the native heap — where bitmap pixels live — while [block]
   * runs. Sampled from a second thread because the render is one synchronous
   * call and the transient copies this guards against never outlive it.
   */
  private fun measuringPeakNativeHeap(block: () -> Unit): Long {
    Runtime.getRuntime().gc()
    Thread.sleep(250)
    val baseline = Debug.getNativeHeapAllocatedSize()
    val peak = AtomicLong(baseline)
    val running = AtomicBoolean(true)
    val sampler = Thread {
      while (running.get()) {
        val allocated = Debug.getNativeHeapAllocatedSize()
        if (allocated > peak.get()) peak.set(allocated)
        try {
          Thread.sleep(2)
        } catch (error: InterruptedException) {
          return@Thread
        }
      }
    }
    sampler.start()
    try {
      block()
    } finally {
      running.set(false)
      sampler.join(2_000)
    }
    return peak.get() - baseline
  }

  private fun renderDirectorySnapshot(): Set<String> =
    File(context.cacheDir, "meme_render").list()?.toSet() ?: emptySet()

  // JPEG is lossy; a flat quadrant survives it to within a few units.
  private fun assertColorNear(message: String, expected: Int, actual: Int) {
    val delta = maxOf(
      Math.abs(Color.red(expected) - Color.red(actual)),
      Math.abs(Color.green(expected) - Color.green(actual)),
      Math.abs(Color.blue(expected) - Color.blue(actual))
    )
    assertTrue(
      "$message: expected #${Integer.toHexString(expected)}, got #${Integer.toHexString(actual)}",
      delta <= 24
    )
  }

  @Test
  fun rendersRotatedAndCroppedProjectAtPlanDimensionsWithRealMosaic() {
    val source = writeFixtureSource("render-fixture-rotated.png")
    val planJson = plan(ROTATED_PLAN, source)
    assertEquals(
      "committed fixture speaks the renderer's plan version",
      MemeImageRenderer.PLAN_VERSION,
      JSONObject(planJson).getInt("version")
    )
    val file = renderedFile(planJson)
    assertPngSignature(file)

    val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
    BitmapFactory.decodeFile(file.absolutePath, bounds)
    // 640x400 rotated 90 -> 400x640, cropped 0.5 x 0.8 -> 200x512.
    assertEquals(200, bounds.outWidth)
    assertEquals(512, bounds.outHeight)

    val rendered = decode(file)
    try {
      // Rotation actually happened: the source's top-left quadrant is now on
      // the output's right-hand side, and the bottom-right one is bottom-left.
      assertEquals("rotated top-left quadrant", TOP_LEFT, rendered.getPixel(150, 10))
      assertEquals("rotated top-right quadrant", TOP_RIGHT, rendered.getPixel(150, 500))
      assertEquals("rotated bottom-right quadrant", BOTTOM_RIGHT, rendered.getPixel(10, 500))
      // Solid cover, drawn in output pixels straight from the plan rect.
      assertEquals("solid cover", Color.parseColor("#FF00FF"), rendered.getPixel(10, 10))

      // Real mosaic: the checkerboard underneath alternates every pixel, so
      // neighbours inside one 16px cell can only match if they were averaged,
      // and the average can be neither pure black nor pure white.
      val cellPixel = rendered.getPixel(110, 440)
      assertEquals("mosaic cell is flat", cellPixel, rendered.getPixel(111, 440))
      assertEquals("mosaic cell is flat", cellPixel, rendered.getPixel(114, 440))
      assertNotEquals("mosaic averaged, not copied", Color.WHITE, cellPixel)
      assertNotEquals("mosaic averaged, not copied", Color.BLACK, cellPixel)
      assertTrue("mosaic average is mid-grey", Color.red(cellPixel) in 60..200)
      assertEquals("mosaic stays opaque", 255, Color.alpha(cellPixel))
    } finally {
      rendered.recycle()
      file.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  @Test
  fun rendersTransparentBackgroundWithBurnedInText() {
    val source = writeFixtureSource("render-fixture-transparent.png")
    val file = renderedFile(plan(TRANSPARENT_PLAN, source))
    assertPngSignature(file)

    val rendered = decode(file)
    try {
      assertEquals(640, rendered.width)
      assertEquals(400, rendered.height)
      // Nothing was drawn in the bottom-right corner, so the alpha channel
      // survived the PNG encode.
      assertEquals("transparent corner", 0, Color.alpha(rendered.getPixel(630, 390)))
      assertEquals("transparent corner", 0, Color.alpha(rendered.getPixel(5, 395)))
      // The solid cover is the only opaque block besides the text.
      assertEquals("solid cover", Color.parseColor("#FF00FF"), rendered.getPixel(10, 10))

      // Burned-in text: outside the cover rect the ONLY possible opaque pixels
      // are the glyph fill and its stroke, so counting them proves real text
      // was rasterized — and both colors must be present.
      var white = 0
      var black = 0
      var opaqueOutsideCover = 0
      for (y in 120 until 400) {
        for (x in 0 until 640) {
          val pixel = rendered.getPixel(x, y)
          if (Color.alpha(pixel) < 255) continue
          opaqueOutsideCover++
          if (Color.red(pixel) > 240 && Color.green(pixel) > 240 && Color.blue(pixel) > 240) white++
          if (Color.red(pixel) < 15 && Color.green(pixel) < 15 && Color.blue(pixel) < 15) black++
        }
      }
      assertTrue("text rasterized ($opaqueOutsideCover opaque px)", opaqueOutsideCover > 500)
      assertTrue("glyph fill present ($white px)", white > 200)
      assertTrue("glyph stroke present ($black px)", black > 200)
    } finally {
      rendered.recycle()
      file.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  @Test
  fun honorsTheDownscaledOutputSizeTheMemoryGuardEmitted() {
    val source = writeFixtureSource("render-fixture-downscaled.png")
    val json = JSONObject(plan(ROTATED_PLAN, source))
    // What buildImageRenderPlan emits when the pixel cap bites: a reduced
    // output with an explicit scale factor. The renderer must allocate exactly
    // that, never the full size.
    json.getJSONObject("output").apply {
      put("widthPx", 100)
      put("heightPx", 256)
      put("downscaled", true)
      put("scale", 0.5)
    }
    val file = renderedFile(json.toString())
    try {
      assertPngSignature(file)
      val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
      BitmapFactory.decodeFile(file.absolutePath, bounds)
      assertEquals(100, bounds.outWidth)
      assertEquals(256, bounds.outHeight)
    } finally {
      file.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  @Test
  fun rejectsAnUnsupportedPlanVersionInsteadOfWritingAFile() {
    val source = writeFixtureSource("render-fixture-version.png")
    val json = JSONObject(plan(ROTATED_PLAN, source)).put("version", 99)
    val before = renderDirectorySnapshot()
    try {
      MemeImageRenderer.render(context, json.toString())
      throw AssertionError("expected an unsupported-version failure")
    } catch (error: IOException) {
      assertTrue(error.message.orEmpty().contains("Unsupported render plan version"))
      assertEquals("rejected plan wrote a file", before, renderDirectorySnapshot())
    } finally {
      File(requireNotNull(source.path)).delete()
    }
  }

  @Test
  fun repeatedRendersStayStableAndDoNotLeakDescriptors() {
    val source = writeFixtureSource("render-fixture-repeat.png")
    val planJson = plan(TRANSPARENT_PLAN, source)
    val written = ArrayList<File>()
    written.add(File(requireNotNull(Uri.parse(MemeImageRenderer.render(context, planJson)).path)))
    val descriptorsBefore = File("/proc/self/fd").list()?.size ?: 0
    var lastLength = 0L
    repeat(5) {
      val file = renderedFile(planJson)
      written.add(file)
      if (lastLength != 0L) assertEquals("deterministic encode", lastLength, file.length())
      lastLength = file.length()
    }
    val descriptorsAfter = File("/proc/self/fd").list()?.size ?: 0
    assertTrue(
      "renderer leaked descriptors: before=$descriptorsBefore after=$descriptorsAfter",
      descriptorsAfter <= descriptorsBefore + 2
    )
    written.forEach { it.delete() }
    File(requireNotNull(source.path)).delete()
  }

  /**
   * RENDER-MEM-001. An 8 MP EXIF-rotated camera JPEG used to be decoded whole
   * (32 MB) and then copied whole again by orientBitmapForExif (another 32 MB,
   * both alive at once) no matter how small the export was. The decode is now
   * sampled down to what the output rect consumes and the orientation rides in
   * the draw matrix, so nothing full-size is ever materialized.
   */
  @Test
  fun rendersALargeExifRotatedSourceWithinABoundedFootprint() {
    val source = writeLargeExifRotatedSource("render-fixture-large.jpg")
    val json = JSONObject(plan(ROTATED_PLAN, Uri.fromFile(source)))
    json.getJSONObject("source").apply {
      put("widthPx", LARGE_SOURCE_HEIGHT)
      put("heightPx", LARGE_SOURCE_WIDTH)
      put("rotation", 0)
      put("crop", JSONObject().put("x", 0).put("y", 0).put("width", 1).put("height", 1))
    }
    // 2448x3264 as displayed, exported at 1/8 — the shape the plan builder
    // emits once the pixel guard bites on a phone photo.
    json.getJSONObject("output").apply {
      put("widthPx", 306)
      put("heightPx", 408)
      put("downscaled", true)
      put("scale", 0.125)
    }
    json.put("layers", JSONArray())

    var file: File? = null
    val peakBytes = measuringPeakNativeHeap { file = renderedFile(json.toString()) }
    val rendered = decode(requireNotNull(file))
    try {
      assertEquals(306, rendered.width)
      assertEquals(408, rendered.height)
      // EXIF orientation 6 rotates the raw frame a quarter turn clockwise, so
      // every raw quadrant has to land on the adjacent display quadrant.
      assertColorNear("exif applied: raw bottom-left", BOTTOM_LEFT, rendered.getPixel(48, 48))
      assertColorNear("exif applied: raw top-left", TOP_LEFT, rendered.getPixel(256, 48))
      assertColorNear("exif applied: raw bottom-right", BOTTOM_RIGHT, rendered.getPixel(48, 360))
      assertColorNear("exif applied: raw top-right", TOP_RIGHT, rendered.getPixel(256, 360))
      // Two full-size copies of this source are 64 MB; the sampled decode plus
      // the 0.5 MB output is nowhere near this bound.
      assertTrue(
        "peak native heap grew by ${peakBytes / (1024 * 1024)} MB during the render",
        peakBytes < 24L * 1024L * 1024L
      )
    } finally {
      rendered.recycle()
      requireNotNull(file).delete()
      source.delete()
    }
  }

  /**
   * RENDER-INT-002. `column * regionWidth / columns` overflows Int once the
   * region is wider than 46340 with a one-pixel cell; the wrapped value lands
   * on a negative pixel index a third of the way across.
   */
  @Test
  fun pixelatesAnExtremeAspectRegionWithoutOverflowingTheCellMath() {
    val width = 70_000
    val target = Bitmap.createBitmap(width, 2, Bitmap.Config.ARGB_8888)
    try {
      val pixels = IntArray(width * 2) { index ->
        if (index % width % 2 == 0) Color.WHITE else Color.BLACK
      }
      target.setPixels(pixels, 0, width, 0, 0, width, 2)
      MemeImageRenderer.drawPixelateMosaic(
        Canvas(target),
        target,
        RectF(0f, 0f, width.toFloat(), 2f),
        1
      )

      // Two-pixel cells over a one-pixel checkerboard: every cell is mid-grey,
      // including the ones past the 46340-pixel overflow point.
      for (x in intArrayOf(0, 30_679, 46_341, width - 1)) {
        val averaged = target.getPixel(x, 0)
        assertEquals("cell at $x averaged", 127, Color.red(averaged))
        assertEquals("cell at $x averaged", 127, Color.blue(averaged))
        assertEquals("cell at $x stays opaque", 255, Color.alpha(averaged))
      }
    } finally {
      target.recycle()
    }
  }

  /**
   * RENDER-DOS-003. Cell count, not region area, is what a mosaic pays for.
   */
  @Test
  fun clampsTheMosaicCellToTheRegionAndSkipsAOnePixelMosaic() {
    // A full 16 MP canvas at pixelSize 1 would be 16M averaged cells; the same
    // floor src/memeImageRenderCore.ts applies keeps it at 65536.
    assertEquals(16, MemeImageRenderer.mosaicCellPx(4000, 4000, 1))
    // A cell the plan can afford is left exactly as asked.
    assertEquals(16, MemeImageRenderer.mosaicCellPx(80, 154, 16))
    assertEquals(1, MemeImageRenderer.mosaicCellPx(64, 64, 1))

    val target = Bitmap.createBitmap(64, 64, Bitmap.Config.ARGB_8888)
    try {
      val pixels = IntArray(64 * 64) { if (it % 2 == 0) Color.WHITE else Color.BLACK }
      target.setPixels(pixels, 0, 64, 0, 0, 64, 64)
      MemeImageRenderer.drawPixelateMosaic(Canvas(target), target, RectF(0f, 0f, 64f, 64f), 1)
      // A one-pixel cell averages each pixel with itself: a no-op, not 4096
      // read-and-repaint round trips.
      assertEquals(Color.WHITE, target.getPixel(0, 0))
      assertEquals(Color.BLACK, target.getPixel(1, 0))
    } finally {
      target.recycle()
    }
  }

  /** RENDER-ALLOC-004. */
  @Test
  fun rejectsAnOutputBeyondThePixelCapInsteadOfAllocatingIt() {
    val source = writeFixtureSource("render-fixture-oversized.png")
    val json = JSONObject(plan(ROTATED_PLAN, source))
    json.getJSONObject("output").put("widthPx", 8000).put("heightPx", 8000)
    val before = renderDirectorySnapshot()
    try {
      MemeImageRenderer.render(context, json.toString())
      throw AssertionError("expected an oversized-output failure")
    } catch (error: IOException) {
      assertTrue(error.message.orEmpty().contains("exceeds"))
      assertEquals("rejected plan wrote a file", before, renderDirectorySnapshot())
    } finally {
      File(requireNotNull(source.path)).delete()
    }
  }

  /**
   * RENDER-VAL-007 / RENDER-VAL-008. NaN passes `<= 0f`, survives `max`, turns
   * the whole matrix into NaN — a background-only PNG that looks like a
   * successful export — and reaches roundToInt as an IllegalArgumentException.
   */
  @Test
  fun rejectsNonFiniteNumbersAsAMalformedPlan() {
    val source = writeFixtureSource("render-fixture-nonfinite.png")
    val malformed = mapOf(
      "NaN crop" to JSONObject(plan(ROTATED_PLAN, source)).also {
        it.getJSONObject("source").getJSONObject("crop").put("width", "NaN")
      },
      "infinite cover rect" to JSONObject(plan(ROTATED_PLAN, source)).also {
        it.getJSONArray("layers").getJSONObject(0).getJSONObject("rect").put("height", "1e999")
      },
      "NaN wrap width" to JSONObject(plan(ROTATED_PLAN, source)).also {
        it.getJSONArray("layers")
          .getJSONObject(2)
          .getJSONObject("spec")
          .getJSONObject("canvas")
          .put("wrapWidthDip", "NaN")
      }
    )
    try {
      for ((label, json) in malformed) {
        val before = renderDirectorySnapshot()
        try {
          MemeImageRenderer.render(context, json.toString())
          throw AssertionError("expected $label to be rejected")
        } catch (error: IOException) {
          assertTrue(
            "$label: ${error.message}",
            error.message.orEmpty().contains("finite") || error.message.orEmpty().contains("range")
          )
          assertEquals("$label wrote a file", before, renderDirectorySnapshot())
        }
      }
    } finally {
      File(requireNotNull(source.path)).delete()
    }
  }

  /**
   * RENDER-MEM-005. The translucency layer is bounded to the text's content
   * box now, so it must still composite the whole glyph run at the right alpha.
   */
  @Test
  fun burnsInTranslucentTextThroughABoundedLayer() {
    val source = writeFixtureSource("render-fixture-translucent.png")
    val json = JSONObject(plan(TRANSPARENT_PLAN, source))
    json.getJSONArray("layers")
      .getJSONObject(1)
      .getJSONObject("spec")
      .getJSONObject("fill")
      .put("opacity", 0.5)
    val file = renderedFile(json.toString())
    val rendered = decode(file)
    try {
      assertEquals("transparent corner survives the layer", 0, Color.alpha(rendered.getPixel(630, 390)))
      var translucent = 0
      var opaque = 0
      for (y in 120 until 400) {
        for (x in 0 until 640) {
          val alpha = Color.alpha(rendered.getPixel(x, y))
          if (alpha in 100..160) translucent++
          if (alpha == 255) opaque++
        }
      }
      assertTrue("half-opacity text rasterized ($translucent px)", translucent > 500)
      assertEquals("nothing outside the cover stayed opaque", 0, opaque)
    } finally {
      rendered.recycle()
      file.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /**
   * RENDER-FILE-006. The output path used to be a pure function of the plan id,
   * so two renders of one project raced into the same file and either one's
   * failure path deleted the other's finished PNG.
   */
  @Test
  fun givesEachRenderOfTheSamePlanItsOwnFile() {
    val source = writeFixtureSource("render-fixture-unique.png")
    val planJson = plan(TRANSPARENT_PLAN, source)
    val first = renderedFile(planJson)
    val second = renderedFile(planJson)
    try {
      assertNotEquals(first.absolutePath, second.absolutePath)
      assertTrue("first render survived the second", first.isFile && first.length() > 0)
      assertEquals("both renders are the same image", first.length(), second.length())
    } finally {
      first.delete()
      second.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /** RENDER-URI-009. */
  @Test
  fun refusesToReadOutsideTheAppSandbox() {
    val rejected = mapOf(
      "file:///system/etc/hosts" to "app-local",
      "/proc/self/environ" to "app-local",
      "http://127.0.0.1/pixel.png" to "scheme"
    )
    for ((uri, expected) in rejected) {
      val json = JSONObject(plan(ROTATED_PLAN, Uri.parse("file:///ignored.png")))
      json.getJSONObject("source").put("uri", uri)
      val before = renderDirectorySnapshot()
      try {
        MemeImageRenderer.render(context, json.toString())
        throw AssertionError("expected $uri to be refused")
      } catch (error: IOException) {
        assertTrue("$uri: ${error.message}", error.message.orEmpty().contains(expected))
        assertEquals("$uri wrote a file", before, renderDirectorySnapshot())
      }
    }
  }

  // --- subject cutouts ------------------------------------------------------

  /**
   * A fully opaque cutout with the given aspect ratio and no transparent margin,
   * so the opaque pixels the renderer produces ARE the placement rectangle.
   */
  private fun writeCutoutFixture(name: String, aspect: Float): File {
    val height = 240
    val width = Math.max(1, Math.round(height * aspect))
    val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
    bitmap.eraseColor(CUTOUT_COLOR)
    val file = File(context.cacheDir, name)
    FileOutputStream(file).use { stream ->
      assertTrue("cutout png encoded", bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream))
    }
    bitmap.recycle()
    return file
  }

  private fun transparentBackground(): JSONObject = JSONObject()
    .put("mode", "transparent")
    .put("color", "#00000000")
    .put("assetUri", JSONObject.NULL)
    .put("blurScale", 0.0)

  /**
   * A minimal plan carrying exactly one subject layer. Hand-built rather than
   * read from an asset because the numbers come from the committed parity
   * fixture, which is itself pinned against the TypeScript builder — so the
   * geometry still originates on the other side of the bridge.
   */
  private fun subjectPlan(
    widthPx: Int,
    heightPx: Int,
    sourceUri: Uri,
    layer: JSONObject,
    background: JSONObject = transparentBackground()
  ): String = JSONObject()
    .put("version", MemeImageRenderer.PLAN_VERSION)
    .put("id", "cutout-test")
    .put("timeUs", 0)
    .put(
      "source",
      JSONObject()
        .put("uri", sourceUri.toString())
        .put("widthPx", 640)
        .put("heightPx", 400)
        .put("rotation", 0)
        .put("flipX", false)
        .put("flipY", false)
        .put(
          "crop",
          JSONObject().put("x", 0.0).put("y", 0.0).put("width", 1.0).put("height", 1.0)
        )
    )
    .put(
      "output",
      JSONObject()
        .put("widthPx", widthPx)
        .put("heightPx", heightPx)
        .put("fullWidthPx", widthPx)
        .put("fullHeightPx", heightPx)
        .put("downscaled", false)
        .put("scale", 1.0)
        .put("maxPixels", 16_000_000)
    )
    .put("background", background)
    .put("layers", JSONArray().put(layer))
    .toString()

  private fun subjectLayer(
    cutoutUri: String,
    rect: JSONObject,
    rotationDegrees: Double = 0.0,
    opacity: Double = 1.0,
    outlineColor: Any = JSONObject.NULL,
    outlinePx: Double = 0.0,
    shadowBlurPx: Double = 0.0,
    shadowOffsetPx: Double = 0.0
  ): JSONObject = JSONObject()
    .put("kind", "subject")
    .put("id", "subject-1")
    .put("cutoutUri", cutoutUri)
    .put("rect", rect)
    .put("rotationDegrees", rotationDegrees)
    .put("opacity", opacity)
    .put("outlineColor", outlineColor)
    .put("outlinePx", outlinePx)
    .put("shadowColor", "#8C000000")
    .put("shadowBlurPx", shadowBlurPx)
    .put("shadowOffsetPx", shadowOffsetPx)

  private class OpaqueBounds(
    val left: Int,
    val top: Int,
    val right: Int,
    val bottom: Int
  ) {
    val width: Int get() = right - left
    val height: Int get() = bottom - top
    override fun toString(): String = "[$left,$top .. $right,$bottom]"
  }

  /**
   * Bounds of the pixels the renderer actually drew.
   *
   * Threshold 32 rather than 255: a half-opacity sticker draws at alpha 127 and
   * bilinear filtering leaves a one-pixel ramp at every edge, so counting only
   * fully opaque pixels would measure something narrower than what was drawn.
   */
  private fun opaqueBounds(bitmap: Bitmap): OpaqueBounds? {
    var left = bitmap.width
    var top = bitmap.height
    var right = -1
    var bottom = -1
    val row = IntArray(bitmap.width)
    for (y in 0 until bitmap.height) {
      bitmap.getPixels(row, 0, bitmap.width, 0, y, bitmap.width, 1)
      for (x in 0 until bitmap.width) {
        if (Color.alpha(row[x]) < 32) continue
        if (x < left) left = x
        if (x > right) right = x
        if (y < top) top = y
        if (y > bottom) bottom = y
      }
    }
    if (right < left || bottom < top) return null
    return OpaqueBounds(left, top, right + 1, bottom + 1)
  }

  private fun readCutoutParityFixtures(): JSONObject =
    JSONObject(
      context.assets.open(CUTOUT_PARITY_FIXTURE).bufferedReader().use { it.readText() }
    )

  /**
   * The parity gate Task 3.2 owes: a cutout has to land on the same FRACTION of
   * the canvas whether it is drawn onto a preview surface or a full-resolution
   * export. Placement comes from the committed fixture (generated by
   * resolveCutoutPlacement in TypeScript); the left-hand side of every
   * comparison is measured off the rendered pixels.
   */
  @Test
  fun placesACutoutOnTheSameFractionOfTheCanvasAtEveryScale() {
    val fixtures = readCutoutParityFixtures()
    assertEquals(
      "fixture version matches the renderer",
      MemeImageRenderer.PLAN_VERSION,
      fixtures.getInt("version")
    )
    val tolerance = fixtures.getDouble("tolerancePx")
    val canvases = fixtures.getJSONArray("canvases")
    val cases = fixtures.getJSONArray("cases")
    val source = writeFixtureSource("render-fixture-cutout-parity.png")
    var verified = 0
    try {
      for (caseIndex in 0 until cases.length()) {
        val parityCase = cases.getJSONObject(caseIndex)
        if (!parityCase.getBoolean("pixelVerifiable")) continue
        val id = parityCase.getString("id")
        val normalized = parityCase.getJSONObject("normalizedRect")
        val placements = parityCase.getJSONArray("placements")
        val first = placements.getJSONObject(0).getJSONObject("rect")
        val aspect = (first.getDouble("width") / first.getDouble("height")).toFloat()
        val cutout = writeCutoutFixture("cutout-parity-$id.png", aspect)
        try {
          for (placementIndex in 0 until placements.length()) {
            val placement = placements.getJSONObject(placementIndex)
            val canvas = canvases.getJSONObject(placement.getInt("canvas"))
            val widthPx = canvas.getInt("widthPx")
            val heightPx = canvas.getInt("heightPx")
            val rendered = renderedFile(
              subjectPlan(
                widthPx = widthPx,
                heightPx = heightPx,
                sourceUri = source,
                layer = subjectLayer(
                  cutoutUri = Uri.fromFile(cutout).toString(),
                  rect = placement.getJSONObject("rect"),
                  rotationDegrees = placement.getDouble("rotationDegrees"),
                  opacity = placement.getDouble("opacity")
                )
              )
            )
            try {
              assertPngSignature(rendered)
              val bitmap = decode(rendered)
              try {
                assertEquals("$id: output width", widthPx, bitmap.width)
                assertEquals("$id: output height", heightPx, bitmap.height)
                val bounds = requireNotNull(opaqueBounds(bitmap)) { "$id: nothing was drawn" }
                val expectedLeft = normalized.getDouble("x") * widthPx
                val expectedTop = normalized.getDouble("y") * heightPx
                val expectedWidth = normalized.getDouble("width") * widthPx
                val expectedHeight = normalized.getDouble("height") * heightPx
                assertNear("$id@${widthPx}x$heightPx left", expectedLeft, bounds.left.toDouble(), tolerance)
                assertNear("$id@${widthPx}x$heightPx top", expectedTop, bounds.top.toDouble(), tolerance)
                assertNear("$id@${widthPx}x$heightPx width", expectedWidth, bounds.width.toDouble(), tolerance)
                assertNear("$id@${widthPx}x$heightPx height", expectedHeight, bounds.height.toDouble(), tolerance)
                // The cutout's own colour has to survive compositing, and its
                // opacity has to be the one the plan asked for.
                val centre = bitmap.getPixel(
                  (bounds.left + bounds.right) / 2,
                  (bounds.top + bounds.bottom) / 2
                )
                assertColorNear("$id: cutout colour", CUTOUT_COLOR, centre or Color.BLACK)
                assertNear(
                  "$id: opacity",
                  placement.getDouble("opacity") * 255,
                  Color.alpha(centre).toDouble(),
                  4.0
                )
                verified += 1
              } finally {
                bitmap.recycle()
              }
            } finally {
              rendered.delete()
            }
          }
        } finally {
          cutout.delete()
        }
      }
      assertTrue("parity: verified $verified renders", verified >= 6)
    } finally {
      File(requireNotNull(source.path)).delete()
    }
  }

  /**
   * Alpha has to survive the cutout path, not just the empty-canvas path: a
   * transparent background plus a subject is the export that makes a cutout
   * worth having, and a PNG that quietly flattened it to black is the failure
   * nobody notices until it is pasted somewhere light.
   */
  @Test
  fun keepsRealTransparencyAroundACompositedCutout() {
    val source = writeFixtureSource("render-fixture-cutout-alpha.png")
    val cutout = writeCutoutFixture("cutout-alpha.png", 1f)
    val rendered = renderedFile(
      subjectPlan(
        widthPx = 400,
        heightPx = 400,
        sourceUri = source,
        layer = subjectLayer(
          cutoutUri = Uri.fromFile(cutout).toString(),
          rect = JSONObject().put("x", 100.0).put("y", 100.0).put("width", 200.0).put("height", 200.0)
        )
      )
    )
    try {
      assertPngSignature(rendered)
      val bitmap = decode(rendered)
      try {
        assertTrue("decoded PNG has an alpha channel", bitmap.hasAlpha())
        assertEquals("corner stays empty", 0, Color.alpha(bitmap.getPixel(2, 2)))
        assertEquals("corner stays empty", 0, Color.alpha(bitmap.getPixel(397, 397)))
        assertEquals("outside the cutout stays empty", 0, Color.alpha(bitmap.getPixel(50, 200)))
        assertEquals("cutout centre is opaque", 255, Color.alpha(bitmap.getPixel(200, 200)))
        assertColorNear("cutout centre colour", CUTOUT_COLOR, bitmap.getPixel(200, 200))
        // The boundary itself: one pixel inside is opaque, well outside is not.
        assertEquals("just inside the edge", 255, Color.alpha(bitmap.getPixel(104, 200)))
        assertEquals("just outside the edge", 0, Color.alpha(bitmap.getPixel(96, 200)))
      } finally {
        bitmap.recycle()
      }
    } finally {
      rendered.delete()
      cutout.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /** The sticker effects have to be visible OUTSIDE the subject, or they are not effects. */
  @Test
  fun drawsTheOutlineAndShadowAroundTheSubject() {
    val source = writeFixtureSource("render-fixture-cutout-sticker.png")
    val cutout = writeCutoutFixture("cutout-sticker.png", 1f)
    val rendered = renderedFile(
      subjectPlan(
        widthPx = 400,
        heightPx = 400,
        sourceUri = source,
        layer = subjectLayer(
          cutoutUri = Uri.fromFile(cutout).toString(),
          rect = JSONObject().put("x", 150.0).put("y", 150.0).put("width", 100.0).put("height", 100.0),
          outlineColor = "#FFFFFFFF",
          outlinePx = 10.0,
          shadowBlurPx = 6.0,
          shadowOffsetPx = 20.0
        )
      )
    )
    try {
      val bitmap = decode(rendered)
      try {
        // Outline: white, a few pixels beyond the subject's left edge.
        val outlinePixel = bitmap.getPixel(145, 200)
        assertTrue("outline is drawn: #${Integer.toHexString(outlinePixel)}", Color.alpha(outlinePixel) > 200)
        assertColorNear("outline colour", Color.WHITE, outlinePixel)
        // Shadow: down-right of the subject, past the outline, dark and partial.
        val shadowPixel = bitmap.getPixel(268, 268)
        val shadowAlpha = Color.alpha(shadowPixel)
        assertTrue("shadow is drawn: alpha $shadowAlpha", shadowAlpha in 20..220)
        assertTrue(
          "shadow is dark: #${Integer.toHexString(shadowPixel)}",
          Color.red(shadowPixel) < 80 && Color.green(shadowPixel) < 80
        )
        // Untouched canvas well away from the sticker is still empty.
        assertEquals("far corner untouched", 0, Color.alpha(bitmap.getPixel(5, 395)))
      } finally {
        bitmap.recycle()
      }
    } finally {
      rendered.delete()
      cutout.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /**
   * The memory question this task reopened: a cutout is a second RGBA bitmap
   * beside the output, and the sticker effects extract an alpha copy of it. A
   * full-frame cutout on a large export must stay inside the stated budget
   * rather than doubling the peak.
   */
  @Test
  fun keepsAFullFrameCutoutInsideABoundedFootprint() {
    val source = writeFixtureSource("render-fixture-cutout-memory.png")
    // 3000x2000 = 6 MP output (24 MB) with a cutout covering all of it.
    val cutout = writeCutoutFixture("cutout-memory.png", 1.5f)
    val planJson = subjectPlan(
      widthPx = 3000,
      heightPx = 2000,
      sourceUri = source,
      layer = subjectLayer(
        cutoutUri = Uri.fromFile(cutout).toString(),
        rect = JSONObject().put("x", 0.0).put("y", 0.0).put("width", 3000.0).put("height", 2000.0),
        outlineColor = "#FFFFFFFF",
        outlinePx = 24.0,
        shadowBlurPx = 18.0,
        shadowOffsetPx = 24.0
      )
    )
    var rendered: File? = null
    val peak = measuringPeakNativeHeap { rendered = renderedFile(planJson) }
    val output = requireNotNull(rendered)
    try {
      val bitmap = decode(output)
      try {
        assertEquals("full-frame cutout still fills the canvas", 3000, bitmap.width)
        assertEquals("cutout centre is opaque", 255, Color.alpha(bitmap.getPixel(1500, 1000)))
      } finally {
        bitmap.recycle()
      }
      // Output bitmap is 24 MB; the cutout decode is capped at a quarter of the
      // 16 MP plan budget (16 MB) and the alpha silhouette is a quarter of that.
      assertTrue(
        "peak native heap growth ${peak / (1024 * 1024)} MB must stay under 96 MB",
        peak < 96L * 1024 * 1024
      )
    } finally {
      output.delete()
      cutout.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /** A replacement background replaces the source; it does not sit under it. */
  @Test
  fun replacesTheBackgroundWithThePickedImage() {
    val source = writeFixtureSource("render-fixture-bg-source.png")
    val replacement = writeCutoutFixture("cutout-background.png", 1.5f)
    val cutout = writeCutoutFixture("cutout-on-background.png", 1f)
    val rendered = renderedFile(
      subjectPlan(
        widthPx = 300,
        heightPx = 200,
        sourceUri = source,
        layer = subjectLayer(
          cutoutUri = Uri.fromFile(cutout).toString(),
          rect = JSONObject().put("x", 100.0).put("y", 50.0).put("width", 100.0).put("height", 100.0)
        ),
        background = JSONObject()
          .put("mode", "image")
          .put("color", "#000000")
          .put("assetUri", Uri.fromFile(replacement).toString())
          .put("blurScale", 0.0)
      )
    )
    try {
      val bitmap = decode(rendered)
      try {
        // Every corner is the replacement's colour: no source quadrant survives.
        for ((x, y) in listOf(2 to 2, 297 to 2, 2 to 197, 297 to 197)) {
          val pixel = bitmap.getPixel(x, y)
          assertEquals("background is opaque at $x,$y", 255, Color.alpha(pixel))
          assertColorNear("background at $x,$y", CUTOUT_COLOR, pixel)
          assertNotEquals("source quadrant leaked at $x,$y", TOP_LEFT, pixel)
        }
      } finally {
        bitmap.recycle()
      }
    } finally {
      rendered.delete()
      cutout.delete()
      replacement.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /** Blurring the source must still show the source, only softened. */
  @Test
  fun blursTheSourceBehindTheSubject() {
    val source = writeFixtureSource("render-fixture-bg-blur.png")
    val sharp = renderedFile(
      subjectPlan(
        widthPx = 320,
        heightPx = 200,
        sourceUri = source,
        layer = JSONObject().put("kind", "unavailable").put("id", "none")
          .put("layerKind", "subject").put("reason", "subject-mask-missing"),
        background = JSONObject()
          .put("mode", "source")
          .put("color", "#00000000")
          .put("assetUri", JSONObject.NULL)
          .put("blurScale", 0.0)
      )
    )
    val blurred = renderedFile(
      subjectPlan(
        widthPx = 320,
        heightPx = 200,
        sourceUri = source,
        layer = JSONObject().put("kind", "unavailable").put("id", "none")
          .put("layerKind", "subject").put("reason", "subject-mask-missing"),
        background = JSONObject()
          .put("mode", "blurred-source")
          .put("color", "#00000000")
          .put("assetUri", JSONObject.NULL)
          .put("blurScale", 0.8)
      )
    )
    try {
      val sharpBitmap = decode(sharp)
      val blurredBitmap = decode(blurred)
      try {
        // Quadrant centres keep their colours: this is still the photo.
        assertColorNear("blurred top-left", TOP_LEFT, blurredBitmap.getPixel(60, 40))
        assertColorNear("blurred bottom-right", BOTTOM_RIGHT, blurredBitmap.getPixel(260, 160))
        assertEquals("blurred background is opaque", 255, Color.alpha(blurredBitmap.getPixel(160, 100)))
        // The quadrant boundary is a hard edge sharp and a gradient blurred, so
        // neighbouring pixels across it differ far less once blurred.
        val sharpStep = channelDistance(
          sharpBitmap.getPixel(158, 100),
          sharpBitmap.getPixel(162, 100)
        )
        val blurredStep = channelDistance(
          blurredBitmap.getPixel(158, 100),
          blurredBitmap.getPixel(162, 100)
        )
        assertTrue(
          "blur softened the quadrant edge (sharp $sharpStep, blurred $blurredStep)",
          blurredStep < sharpStep / 2
        )
      } finally {
        sharpBitmap.recycle()
        blurredBitmap.recycle()
      }
    } finally {
      sharp.delete()
      blurred.delete()
      File(requireNotNull(source.path)).delete()
    }
  }

  /** A background the user picked and we cannot read is a failure, not a fallback. */
  @Test
  fun refusesAReplacementBackgroundItCannotRead() {
    val source = writeFixtureSource("render-fixture-bg-missing.png")
    val missing = File(context.cacheDir, "cutout-background-missing.png")
    missing.delete()
    val before = renderDirectorySnapshot()
    try {
      MemeImageRenderer.render(
        context,
        subjectPlan(
          widthPx = 200,
          heightPx = 200,
          sourceUri = source,
          layer = JSONObject().put("kind", "unavailable").put("id", "none")
            .put("layerKind", "subject").put("reason", "subject-mask-missing"),
          background = JSONObject()
            .put("mode", "image")
            .put("color", "#000000")
            .put("assetUri", Uri.fromFile(missing).toString())
            .put("blurScale", 0.0)
        )
      )
      throw AssertionError("expected an unreadable replacement background to fail")
    } catch (error: IOException) {
      assertTrue(
        "names the replacement background: ${error.message}",
        error.message.orEmpty().contains("replacement background")
      )
      assertEquals("failed render wrote a file", before, renderDirectorySnapshot())
    } finally {
      File(requireNotNull(source.path)).delete()
    }
  }

  private fun assertNear(message: String, expected: Double, actual: Double, tolerance: Double) {
    assertTrue(
      "$message: expected ${"%.2f".format(expected)} +/- $tolerance, got ${"%.2f".format(actual)}",
      Math.abs(expected - actual) <= tolerance
    )
  }

  private fun channelDistance(first: Int, second: Int): Int = maxOf(
    Math.abs(Color.red(first) - Color.red(second)),
    Math.abs(Color.green(first) - Color.green(second)),
    Math.abs(Color.blue(first) - Color.blue(second))
  )

}
