package expo.modules.memegetbg

import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.io.IOException
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Device proof that the native overlay evaluator and the editor preview agree.
 *
 * The fixture in `assets/dynamic_overlay_parity_fixtures.json` is generated by
 * `buildMotionParityFixtures` in src/memeVideoMotionCore.ts, and a Jest test
 * fails if the committed copy is anything other than what the TypeScript
 * evaluator produces. So the expectations here are the PREVIEW's own answers, and
 * every assertion below runs [MemeDynamicOverlay.evaluateAt] to meet them.
 *
 * That is the point worth being pedantic about: asserting the tolerance constant,
 * or re-deriving the expectation in Kotlin, would prove nothing. The numbers on
 * the left of every comparison came off the other side of the bridge.
 */
@RunWith(AndroidJUnit4::class)
class MemeDynamicOverlayInstrumentedTest {
  private companion object {
    const val TAG = "MemeDynamicOverlay"
    const val FIXTURE = "dynamic_overlay_parity_fixtures.json"
  }

  private fun readFixtures(): JSONObject {
    val context = InstrumentationRegistry.getInstrumentation().targetContext
    val json = context.assets.open(FIXTURE).bufferedReader().use { it.readText() }
    return JSONObject(json)
  }

  @Test
  fun nativeEvaluationMatchesPreviewAtEverySampledTimestamp() {
    val fixtures = readFixtures()
    assertEquals(
      "fixture version must match the evaluator",
      MemeDynamicOverlay.FIXTURE_VERSION,
      fixtures.getInt("version")
    )
    val toleranceUnits = fixtures.getDouble("toleranceUnits")
    assertTrue("tolerance must be positive", toleranceUnits > 0.0)

    val cases = fixtures.getJSONArray("cases")
    assertTrue("fixture carries no cases", cases.length() >= 4)

    var visibleSamples = 0
    var absentSamples = 0
    var worstDrift = 0.0
    var worstLabel = ""
    for (caseIndex in 0 until cases.length()) {
      val parityCase = cases.getJSONObject(caseIndex)
      val id = parityCase.getString("id")
      val track = MemeDynamicOverlay.parseTrack(parityCase)
      val samples = parityCase.getJSONArray("samples")
      assertTrue("$id has too few samples", samples.length() >= 5)

      for (sampleIndex in 0 until samples.length()) {
        val sample = samples.getJSONObject(sampleIndex)
        val timeUs = sample.getLong("timeUs")
        val expected = if (sample.getBoolean("visible")) {
          visibleSamples += 1
          MemeDynamicOverlay.Transform(
            centerX = sample.getDouble("centerX"),
            centerY = sample.getDouble("centerY"),
            scale = sample.getDouble("scale"),
            rotationDegrees = sample.getDouble("rotationDegrees"),
            opacity = sample.getDouble("opacity")
          )
        } else {
          absentSamples += 1
          null
        }

        val actual = MemeDynamicOverlay.evaluateAt(track, timeUs)
        val drift = MemeDynamicOverlay.compare(expected, actual)
        assertTrue(
          "$id at ${timeUs}us: preview says ${describe(expected)}, native says ${describe(actual)}",
          drift.visibilityMatches
        )
        assertTrue(
          "$id at ${timeUs}us drifted ${drift.maxUnits} units, over the $toleranceUnits tolerance: " +
            "preview ${describe(expected)} native ${describe(actual)}",
          drift.withinTolerance(toleranceUnits)
        )
        if (drift.maxUnits > worstDrift) {
          worstDrift = drift.maxUnits
          worstLabel = "$id@${timeUs}us"
        }
      }
    }

    // A passing tolerance assertion is only convincing if the number it passed on
    // and the sample count behind it are both visible.
    Log.i(
      TAG,
      "parity: cases=${cases.length()} samples=${visibleSamples + absentSamples} " +
        "visible=$visibleSamples absent=$absentSamples maxDrift=$worstDrift" +
        (if (worstLabel.isEmpty()) "" else " at $worstLabel") +
        " tolerance=$toleranceUnits"
    )
    // Both answers have to be exercised, or an evaluator that always reported one
    // of them would pass everything above.
    assertTrue("fixture never samples a visible overlay", visibleSamples >= 20)
    assertTrue("fixture never samples an absent overlay", absentSamples >= 4)
    // The tolerance above is the documented ceiling, not the bar. Both sides run
    // the same double arithmetic in the same order and then round to the same
    // 1e-12, so they have to agree to the BIT — and the fixture carries samples
    // where that rounding changes the double (a Jest test asserts it does), so
    // an evaluator that skipped the rounding would land here at ~1e-13 rather
    // than at zero and still be inside the tolerance.
    assertEquals("native and preview must agree exactly, not merely closely", 0.0, worstDrift, 0.0)
  }

  @Test
  fun theComparisonItselfCanFail() {
    val fixtures = readFixtures()
    val toleranceUnits = fixtures.getDouble("toleranceUnits")
    val parityCase = fixtures.getJSONArray("cases").getJSONObject(0)
    val track = MemeDynamicOverlay.parseTrack(parityCase)
    val samples = parityCase.getJSONArray("samples")

    var checked = 0
    for (index in 0 until samples.length()) {
      val sample = samples.getJSONObject(index)
      if (!sample.getBoolean("visible")) continue
      val actual = requireNotNull(MemeDynamicOverlay.evaluateAt(track, sample.getLong("timeUs")))
      // A drift a thousand times the tolerance is still invisible on screen, and
      // it must still be rejected — otherwise the tolerance is decoration.
      val nudged = actual.copy(centerX = actual.centerX + toleranceUnits * 1_000.0)
      assertFalse(
        "a ${toleranceUnits * 1_000.0} unit drift passed as agreement",
        MemeDynamicOverlay.compare(nudged, actual).withinTolerance(toleranceUnits)
      )
      // Absent versus present is never within tolerance either.
      assertFalse(
        "an absent overlay compared equal to a drawn one",
        MemeDynamicOverlay.compare(actual, null).withinTolerance(toleranceUnits)
      )
      checked += 1
    }
    assertTrue("no visible sample to perturb", checked > 0)
  }

  @Test
  fun eachClauseOfTheContractIsWhatMovesTheAnswer() {
    val base = MemeDynamicOverlay.Track(
      activeStartUs = 1_000_000L,
      activeEndUs = 5_000_000L,
      keyframes = listOf(
        MemeDynamicOverlay.Keyframe(2_000_000L, 0.2, 0.3, 1.0, 0.0, 1.0, hold = false),
        MemeDynamicOverlay.Keyframe(4_000_000L, 0.6, 0.7, 2.0, 90.0, 0.0, hold = false)
      )
    )

    // Absent outside the range, on both sides, and present exactly on the edges.
    assertNull(MemeDynamicOverlay.evaluateAt(base, 999_999L))
    assertNull(MemeDynamicOverlay.evaluateAt(base, 5_000_001L))
    assertEquals(0.2, requireNotNull(MemeDynamicOverlay.evaluateAt(base, 1_000_000L)).centerX, 0.0)
    assertEquals(0.6, requireNotNull(MemeDynamicOverlay.evaluateAt(base, 5_000_000L)).centerX, 0.0)

    // Linear midpoint, and a hold that releases on its next keyframe rather than
    // one microsecond early.
    val midpoint = requireNotNull(MemeDynamicOverlay.evaluateAt(base, 3_000_000L))
    assertEquals(0.4, midpoint.centerX, 0.0)
    assertEquals(1.5, midpoint.scale, 0.0)
    assertEquals(45.0, midpoint.rotationDegrees, 0.0)
    assertEquals(0.5, midpoint.opacity, 0.0)

    val held = base.copy(keyframes = listOf(base.keyframes[0].copy(hold = true), base.keyframes[1]))
    assertEquals(0.2, requireNotNull(MemeDynamicOverlay.evaluateAt(held, 3_999_999L)).centerX, 0.0)
    assertEquals(0.6, requireNotNull(MemeDynamicOverlay.evaluateAt(held, 4_000_000L)).centerX, 0.0)

    // Rounding is the TypeScript rounding: 0.2 + 0.4 * 0.25 lands on 0.3 exactly
    // rather than on 0.30000000000000004.
    val quarter = base.copy(
      keyframes = listOf(
        MemeDynamicOverlay.Keyframe(1_000_000L, 0.2, 0.0, 1.0, 0.0, 1.0, hold = false),
        MemeDynamicOverlay.Keyframe(5_000_000L, 0.6, 0.0, 1.0, 0.0, 1.0, hold = false)
      )
    )
    assertEquals(0.3, requireNotNull(MemeDynamicOverlay.evaluateAt(quarter, 2_000_000L)).centerX, 0.0)
  }

  @Test
  fun aMalformedTrackIsRejectedRatherThanEvaluated() {
    val unsorted = JSONObject(
      """
      {"activeStartUs":0,"activeEndUs":1000,"keyframes":[
        {"timeUs":500,"centerX":0.5,"centerY":0.5,"scale":1,"rotationDegrees":0,"opacity":1,"easing":"linear"},
        {"timeUs":100,"centerX":0.5,"centerY":0.5,"scale":1,"rotationDegrees":0,"opacity":1,"easing":"linear"}
      ]}
      """.trimIndent()
    )
    val notFinite = JSONObject(
      """
      {"activeStartUs":0,"activeEndUs":1000,"keyframes":[
        {"timeUs":0,"centerX":"NaN","centerY":0.5,"scale":1,"rotationDegrees":0,"opacity":1,"easing":"linear"}
      ]}
      """.trimIndent()
    )
    val empty = JSONObject("""{"activeStartUs":0,"activeEndUs":1000,"keyframes":[]}""")

    for (malformed in listOf(unsorted, notFinite, empty)) {
      try {
        MemeDynamicOverlay.parseTrack(malformed)
        throw AssertionError("parseTrack accepted a malformed track: $malformed")
      } catch (error: IOException) {
        assertTrue("rejection must say why", !error.message.isNullOrBlank())
        Log.i(TAG, "rejected: ${error.message}")
      }
    }
  }

  private fun describe(transform: MemeDynamicOverlay.Transform?): String =
    transform?.let {
      "x=${it.centerX} y=${it.centerY} scale=${it.scale} rot=${it.rotationDegrees} a=${it.opacity}"
    } ?: "absent"
}
