// Make debug builds install as a SEPARATE app from the real one.
//
// Why this exists: debug and release are both signed with the same key (see
// withFixedDebugKeystore) and, by default, share one applicationId. So
// `adb install -r` of a dev build succeeds and REPLACES the installed app.
// Android scopes private storage to the applicationId, so testing a dev build
// on the phone that holds the real library is one command away from exactly the
// data loss src/appIdentity.test.ts warns about — and that warning is not
// hypothetical, the library was destroyed once already.
//
// With this plugin the dev build is com.memeget.app.debug: its own sandbox, its
// own icon, installed ALONGSIDE the real app instead of over it. The release id
// is untouched and still ships as com.memeget.app, which is what appIdentity
// pins. The FileProvider authority in memeget-bg already interpolates
// ${applicationId}, so it follows automatically and the two apps cannot collide
// on a provider authority either (Android would refuse the install if they did).
//
// The debug app also gets its own name. Both builds otherwise present as the
// same icon with the same label, and expo-share-intent puts both in the system
// share sheet — a wrong tap there is how you end up importing memes into the
// throwaway sandbox, or worse, believing the real library is empty. The label
// override lives in the debug source set, which overrides main WITHOUT the
// duplicate-resource error that a resValue would cause, because Expo already
// generates app_name into main's strings.xml.
const { withAppBuildGradle, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SUFFIX = '.debug';
const DEBUG_APP_LABEL = 'Memeget Dev';

/**
 * Insert `applicationIdSuffix` into buildTypes.debug.
 *
 * Kept pure and exported so it can be tested without running a prebuild: the
 * generated android/ tree is gitignored, so a test that reads build.gradle would
 * pass locally off a stale working copy and fail in a clean checkout.
 */
function addDebugApplicationIdSuffix(gradle, suffix = SUFFIX) {
  if (new RegExp(`applicationIdSuffix\\s+["']${suffix.replace('.', '\\.')}["']`).test(gradle)) {
    return gradle; // already applied — prebuild is not always a clean slate
  }

  // Anchor inside buildTypes. `signingConfigs` also contains a `debug {` block,
  // and putting an applicationIdSuffix there is silently meaningless.
  const buildTypes = /(\n\s*buildTypes\s*\{)/.exec(gradle);
  if (!buildTypes) {
    throw new Error(
      '[withSeparateDebugApp] no buildTypes block in app/build.gradle. Refusing to ' +
        'continue: silently skipping would hand back a dev build that installs over ' +
        'the real app and wipes its library.'
    );
  }

  const from = buildTypes.index + buildTypes[0].length;
  const debugBlock = /\n(\s*)debug\s*\{/.exec(gradle.slice(from));
  if (!debugBlock) {
    throw new Error(
      '[withSeparateDebugApp] buildTypes has no debug block; cannot isolate the dev app.'
    );
  }

  const at = from + debugBlock.index + debugBlock[0].length;
  const indent = `${debugBlock[1]}    `;
  return `${gradle.slice(0, at)}\n${indent}applicationIdSuffix '${suffix}'${gradle.slice(at)}`;
}

function debugStringsXml(label = DEBUG_APP_LABEL) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withSeparateDebugApp.js. The dev build installs
     alongside the real app; this is what keeps them apart on the home screen
     and in the share sheet. -->
<resources>
  <string name="app_name">${label}</string>
</resources>
`;
}

module.exports = function withSeparateDebugApp(config) {
  const withGradle = withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `[withSeparateDebugApp] expected a groovy build.gradle, got ${cfg.modResults.language}.`
      );
    }
    cfg.modResults.contents = addDebugApplicationIdSuffix(cfg.modResults.contents);
    return cfg;
  });

  return withDangerousMod(withGradle, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'debug', 'res', 'values');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'strings.xml'), debugStringsXml());
      return cfg;
    },
  ]);
};

module.exports.addDebugApplicationIdSuffix = addDebugApplicationIdSuffix;
module.exports.debugStringsXml = debugStringsXml;
module.exports.SUFFIX = SUFFIX;
